Repository Seila-dev/watchlist-server, pull requests merged in 2025-09, with the labels that each got.

#2 Config/cloudflare r2 jest
  .env.example
  .eslintrc.js
  README.md
  jsconfig.json
  package-lock.json
  package.json
  src/controllers/ContentController.js
  src/database/client.js
  src/middlewares/Auth.js
  src/queue/redis.js
  src/routes/ContentRoutes.js
  src/server.js
  src/storage/ConfigR2.js
  src/tests/sum.test.js
  src/utils/logger.js
Labels: documentation, config

#3 feat: add all auth-routes, fix server imports, need to test auth routes
  package-lock.json
  package.json
  prisma/schema.prisma
  src/controllers/AuthController.js
  src/controllers/AuthGoogleController.js
  src/controllers/GetCurrentUser.js
  src/controllers/UsersController.js
  src/errors/HandleGlobalError.js
  src/middlewares/Auth.js
  src/routes/AuthRoutes.js
  src/routes/UsersRoutes.js
  src/server.js
Labels: enhancement, config

#4 fix: fix migration and proxy
  prisma/migrations/20250918143630_setup_initial/migration.sql
  src/server.js
Labels: bug

#5 fix: fix returns on auth controller
  src/controllers/AuthController.js
Labels: bug

#7 fix: fix port
  src/server.js
Labels: bug

#9 test: test
  src/controllers/AuthController.js
Labels: bug

#12 feat: implement content management improvements
  src/controllers/ContentController.js
  src/repositories/ContentRepository.js
  src/routes/ContentRoutes.js
  src/services/ContentService.js
Labels: enhancement, refactor
